### ISSUE TITLE
ReferenceError: global is not defined

### ISSUE THREAD

**Issue by StefSchenkelaars** [oscartbeaumont/vite-plugin-relay#171]
I was trying to get this plugin up and running in my own project but bumped into the following error `ReferenceError: global is not defined`. So then the exploration started: I've checked out this repo and tried to boot the example app and I got the same error.

It happens only when running the dev server, the production build goes just fine. Therefore, the end-to-end tests are not failing. I could "fix" it by changing the `vite.config.ts` content with:

```typescript
import { defineConfig } from "vite";
import reactRefresh from "@vitejs/plugin-react-refresh";
import relay from "vite-plugin-relay";

export default defineConfig({
  define: {
    global: {
      global: 'globalThis'
    }
  },
  plugins: [reactRefresh(), relay],
});
```

but actually I have no idea why that works. I've noticed that something similar has been changed in #152 but I'm not too much into this to completely oversee the impact. 

<details>
<summary>Full Stacktrace</summary>

```
RelayReferenceMarker.js:333 Uncaught ReferenceError: global is not defined
    at node_modules/relay-runtime/lib/store/RelayPublishQueue.js (RelayReferenceMarker.js:333)
    at __require2 (chunk-ENMAWK7U.js?v=1254bb04:36)
    at node_modules/relay-runtime/lib/store/RelayModernEnvironment.js (RelayModernStore.js:652)
    at __require2 (chunk-ENMAWK7U.js?v=1254bb04:36)
    at node_modules/relay-runtime/lib/index.js (index.js:10)
    at __require2 (chunk-ENMAWK7U.js?v=1254bb04:36)
    at node_modules/relay-runtime/index.js (index.js:10)
    at __require2 (chunk-ENMAWK7U.js?v=1254bb04:36)
    at node_modules/react-relay/lib/ReactRelayContext.js (ReactRelayContext.js:15)
    at __require2 (chunk-ENMAWK7U.js?v=1254bb04:36)
```

</details>

**Comment by oscartbeaumont** [comment]
Add something like the following to your `index.html`.
```html
<script>let global = globalThis;</script>
```
The definition was recently removed from this Vite plugin as it was causing issues with some use cases and is also against Vite's recommendations for plugin authors. When removing it I tested the example project and found no issues so I must have done something incorrectly. I will fix the example and add some documentation about this to the README at some point in the next week.
Thanks for letting me know about this issue.

**Comment by StefSchenkelaars** [comment]
Thanks for the quick reply. I've made a PR to update the tests setup to use the dev server by default: https://github.com/oscartbeaumont/vite-plugin-relay/pull/172

**Comment by oscartbeaumont** [comment]
Documentation for this has been added to the README so I am going to close this issue.
