### ISSUE TITLE
Relay 13 support - Rust compiler: definition of 'XYZQuery' appears to have changed

### ISSUE THREAD

**Issue by sync** [oscartbeaumont/vite-plugin-relay#211]
In order to avoid having this issue when using Relay 13: https://github.com/facebook/relay/issues/3437 we would need to upgrade the `babel-plugin-relay` to `^13.0.0`.

Before I sent you a PR would have happy to include this change ? it looks like it might be a breaking change for all the non 13.x relay user.

I've tested the upgrade on a complicated relay + Vite codebase and except for this required fix everything else is working.

**Comment by oscartbeaumont** [comment]
Please send the PR through. I have been intending to release a new version of this package for a few days so once you get that though I will release an update.
I will release it as version `2.0.0` and this should help with the backwards compatibility aspect.

**Comment by sync** [comment]
cool give me till the end of my day and I'll sent this trough in about 8 hours

**Comment by sync** [comment]
I forgot will do this soonish. Also we now need to upgrade babel-plugin-relay to 13.0.1 and rename `eagerESModules ` to `eagerEsModules `. Tested on my side with those changes everything works. 

these are the relay changes: https://github.com/facebook/relay/pull/3724/files

**Comment by cliedeman** [comment]
@oscartbeaumont Can you please check #303

**Comment by tobias-tengler** [comment]
My PR should address these issues, by moving the `babel-plugin-relay` dependency out of this plugin: https://github.com/oscartbeaumont/vite-plugin-relay/pull/424
