### ISSUE TITLE
Expose a config option for artifactDirectory

### ISSUE THREAD

**Issue by kejistan** [oscartbeaumont/vite-plugin-relay#309]
relay-compiler and babel-plugin-relay have an `artifactDirectory` config option to control the location of the generated files. The babel plugin and the relay-compiler config need to have the same location configure to work correctly. Currently this plugin doesn't expose a mechanism for configuring this so users cannot use this option in the relay compiler.

**Comment by cliedeman** [comment]
Are you using a `relay.config.js`?

https://relay.dev/docs/getting-started/installation-and-setup/#compiler-configuration

**Comment by cliedeman** [comment]
I see.

From version 13 it will [read the relay.config.js](https://github.com/facebook/relay/blob/v13.0.0/packages/babel-plugin-relay/BabelPluginRelay.js#L17)

In the meantime you copy the plugin into your project as a temporary solution

vite.config.ts
```ts
import type { Plugin } from "vite";
import { defineConfig } from "vite";
import { transformSync } from "@babel/core";

function relay(): Plugin {
  return {
    name: "vite:relay",
    transform(src, id) {
      let code = src;
      if (/.(t|j)sx?/.test(id) && src.includes("graphql`")) {
        const out = transformSync(src, {
          plugins: [
            [
              require.resolve("babel-plugin-relay"),
              {
                // TODO: your custom config
              },
            ],
          ],
          code: true,
        });

        if (!out?.code) throw new Error("vite-plugin-react Failed to build");
        code = out.code;
      }

      return {
        code,
        map: null,
      };
    },
  };
}

export default defineConfig({
  plugins: [..., relay],
});
```

**Comment by kejistan** [comment]
I came back to this and figured out why it was failing. It wasn't the inability to specify the `artifactDirectory` in the plugin, you're right that the plugin can find it from the config file directly. It was actually the fact that the babel plugin is invoked without any file information: https://github.com/oscartbeaumont/vite-plugin-relay/pull/334

**Comment by tobias-tengler** [comment]
This should also be resolved by my PR: https://github.com/oscartbeaumont/vite-plugin-relay/pull/424
