### ISSUE TITLE
Is this supposed to make `relay-compiler` automatically run when `vite` is invoked?

### ISSUE THREAD

**Issue by virtuoushub** [oscartbeaumont/vite-plugin-relay#467]
currently I have:
```json
  "scripts": {
    "dev": "pnpm relay && vite",
    "build": "pnpm relay && tsc && vite build",
    "preview": "vite preview",
    "relay": "relay-compiler"
  },
```
in my `package.json`.

I was hoping that I could just have something more like:

```diff
  "scripts": {
-    "dev": "pnpm relay && vite",
+    "dev": "vite",
-    "build": "pnpm relay && tsc && vite build",
+    "build": "tsc && vite build",
    "preview": "vite preview",
    "relay": "relay-compiler"
  },
```

by using this plugin, but maybe I am not understanding this plugin's usecase.

**Comment by tobias-tengler** [comment]
The relay-compiler has nothing to do with this package. It's only used to generate Relay's artifacts once you change the GraphQL schema or a query / fragment in your code base. Running the compiler once when you start is rather pointless. It should best be run with the --watch flag by itself as to correctly keep Relay's artifacts in sync with the code you write.

The purpose of this plugin is to invoke the babel-plugin-relay, which in turn transforms the fragment and query definitions you have in your code as strings to the Relay artifacts that the compiler is generating. Hope this helps :)
